name: creating   workflow 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 For  ORG

on: 
  push:
    branches:
    - DEVELOP
      - main
      - '*/*'  # Include pushes to any branch
  pull_request:
    types: [closed]  # Trigger when a pull request is closed (merged)

jobs:
  SFDX-CLI-Deploy: 
    runs-on: ubuntu-latest

    steps:
      - run: echo "GitHub Action running on ${{ runner.os }}"
      - run: echo "Retrieving ${{ github.ref }} from ${{ github.repository }}."
      - uses: actions/checkout@v2
      - run: npm install sfdx-cli -g
      - run: echo "${{ secrets.SALESFORCE_666_JWT_SECRET_KEY }}" > server.key
      - run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_666_CONSUMER_KEY  }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_666_DEVHUB_USERNAME }} --setdefaultdevhubusername
      - run: sfdx force:source:deploy --manifest=manifest/package.xml --testlevel=RunLocalTests -u ${{ secrets.SALESFORCE_666_DEVHUB_USERNAME }}
